import os
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
import numpy as np
import pandas as pd
import seaborn as sns

# Clean formatting style (clutter-free presentation)
plt.rcParams["font.family"] = "sans-serif"
plt.rcParams["axes.edgecolor"] = "#cccccc"
plt.rcParams["axes.linewidth"] = 0.8

base_dir = os.path.dirname(os.path.abspath(__file__))
data_path = os.path.join(
    base_dir, "..", "Day_1", "Dataset", "SampleSuperstore", "Cleaned_SampleSuperstore.csv"
)
if not os.path.exists(data_path):
  data_path = os.path.join(
      base_dir, "..", "Day_1", "Dataset", "SampleSuperstore", "SampleSuperstore.csv"
  )

print(f"Loading data from: {data_path}")
df = pd.read_csv(data_path)
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

slides_dir = os.path.join(base_dir, "slides")
os.makedirs(slides_dir, exist_ok=True)
pdf_path = os.path.join(base_dir, "Superstore_Data_Story.pdf")

pdf = PdfPages(pdf_path)

# ==========================================
# SLIDE 1: CONTEXT
# ==========================================
fig, ax = plt.subplots(figsize=(11, 6.2))
category_perf = (
    df.groupby("category")[["sales", "profit"]].sum().reset_index()
)

x = np.arange(len(category_perf))
width = 0.35

ax.bar(
    x - width / 2,
    category_perf["sales"],
    width,
    label="Revenue ($)",
    color="#3b82f6",
)
ax.bar(
    x + width / 2,
    category_perf["profit"],
    width,
    label="Profit ($)",
    color="#10b981",
)

ax.set_xticks(x)
ax.set_xticklabels(category_perf["category"], fontsize=12, fontweight="bold")
ax.grid(False)
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.legend(frameon=False, fontsize=11)
ax.set_ylabel("Total USD ($)", fontsize=11)

plt.title(
    "Slide 1: High Top-Line Revenue Fails to Yield Proportional Profits in Furniture",
    fontsize=14,
    fontweight="bold",
    pad=18,
    loc="left",
)
plt.suptitle(
    "Takeaway: Furniture matches Office Supplies in revenue ($742K) but produces only a fraction of its net profit ($18.4K vs $122.5K).",
    fontsize=10.5,
    y=0.92,
    x=0.08,
    ha="left",
    color="#475569",
)

plt.tight_layout(rect=[0, 0, 1, 0.90])
plt.savefig(os.path.join(slides_dir, "slide1_context.png"), dpi=300)
pdf.savefig(fig)
plt.close()

# ==========================================
# SLIDE 2: PROBLEM IDENTIFICATION (Margin Comparison)
# ==========================================
fig, ax = plt.subplots(figsize=(11, 6.2))
category_perf["margin"] = (
    category_perf["profit"] / category_perf["sales"]
) * 100
colors = [
    "#ef4444" if val < 5 else "#3b82f6" for val in category_perf["margin"]
]

bars = ax.bar(
    category_perf["category"],
    category_perf["margin"],
    color=colors,
    width=0.45,
)
ax.grid(False)
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.set_ylabel("Profit Margin (%)", fontsize=11)
ax.axhline(10, color="#64748b", linestyle="--", linewidth=1)
ax.text(
    2.2,
    10.3,
    "Target Benchmark: 10%",
    color="#64748b",
    fontsize=10,
    fontstyle="italic",
)

for bar in bars:
  height = bar.get_height()
  ax.annotate(
      f"{height:.1f}%",
      xy=(bar.get_x() + bar.get_width() / 2, height),
      xytext=(0, 4),
      textcoords="offset points",
      ha="center",
      fontweight="bold",
      fontsize=11,
  )

plt.title(
    "Slide 2: Furniture Suffers Severe Margin Collapse Down to 2.49%",
    fontsize=14,
    fontweight="bold",
    pad=18,
    loc="left",
)
plt.suptitle(
    "Takeaway: Technology and Office Supplies maintain healthy 17.4% and 16.5% margins, while Furniture drops to an unsustainable 2.49%.",
    fontsize=10.5,
    y=0.92,
    x=0.08,
    ha="left",
    color="#475569",
)

plt.tight_layout(rect=[0, 0, 1, 0.90])
plt.savefig(os.path.join(slides_dir, "slide2_margin_problem.png"), dpi=300)
pdf.savefig(fig)
plt.close()

# ==========================================
# SLIDE 3: EVIDENCE A (Sub-Category Culprits)
# ==========================================
fig, ax = plt.subplots(figsize=(11, 6.2))
subcat_profit = (
    df.groupby("sub_category")["profit"].sum().sort_values(ascending=True)
)
sub_colors = ["#dc2626" if val < 0 else "#94a3b8" for val in subcat_profit]

bars = ax.barh(subcat_profit.index, subcat_profit.values, color=sub_colors)
ax.grid(False)
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.axvline(0, color="black", linewidth=0.9)
ax.set_xlabel("Net Profit ($)", fontsize=11)

plt.title(
    "Slide 3: Tables and Bookcases Are the Primary Profit Drains Across the Catalog",
    fontsize=14,
    fontweight="bold",
    pad=18,
    loc="left",
)
plt.suptitle(
    "Takeaway: Tables (-$17,725) and Bookcases (-$3,473) single-handedly wipe out the surplus generated by Chairs and Furnishings.",
    fontsize=10.5,
    y=0.92,
    x=0.08,
    ha="left",
    color="#475569",
)

plt.tight_layout(rect=[0, 0, 1, 0.90])
plt.savefig(os.path.join(slides_dir, "slide3_subcat_evidence.png"), dpi=300)
pdf.savefig(fig)
plt.close()

# ==========================================
# SLIDE 4: EVIDENCE B (The Root Cause - Discounting)
# ==========================================
fig, ax = plt.subplots(figsize=(11, 6.2))
disc_analysis = (
    df.groupby("discount")
    .agg(avg_profit=("profit", "mean"), order_count=("sales", "count"))
    .reset_index()
)

ax.plot(
    disc_analysis["discount"] * 100,
    disc_analysis["avg_profit"],
    marker="o",
    color="#e11d48",
    linewidth=2.8,
)
ax.axhline(0, color="black", linestyle="-", linewidth=0.9)
ax.axvline(20, color="#f59e0b", linestyle="--", linewidth=1.2)
ax.text(
    21,
    -120,
    "The 20% Threshold: Margin Bleed Begins",
    color="#d97706",
    fontweight="bold",
    fontsize=10.5,
)

ax.grid(False)
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.set_xlabel("Promotional Discount Level (%)", fontsize=11)
ax.set_ylabel("Average Profit per Order ($)", fontsize=11)

plt.title(
    "Slide 4: Discount Rates Exceeding 20% Systematically Destroy Bottom-Line Margin",
    fontsize=14,
    fontweight="bold",
    pad=18,
    loc="left",
)
plt.suptitle(
    "Takeaway: Transactions discounted above 20% incur progressive net losses, reaching an average loss of over $200 per order at 70%+ discount.",
    fontsize=10.5,
    y=0.92,
    x=0.08,
    ha="left",
    color="#475569",
)

plt.tight_layout(rect=[0, 0, 1, 0.90])
plt.savefig(os.path.join(slides_dir, "slide4_discount_evidence.png"), dpi=300)
pdf.savefig(fig)
plt.close()

# ==========================================
# SLIDE 5: EVIDENCE C (Geographic Concentration)
# ==========================================
fig, ax = plt.subplots(figsize=(11, 6.2))
furn_reg = (
    df[df["category"] == "Furniture"]
    .groupby("region")[["sales", "profit"]]
    .sum()
    .reset_index()
)

bars = ax.bar(
    furn_reg["region"],
    furn_reg["profit"],
    color=[
        "#ef4444" if val < 0 else "#10b981" for val in furn_reg["profit"]
    ],
    width=0.45,
)
ax.axhline(0, color="black", linewidth=0.9)
ax.grid(False)
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.set_ylabel("Furniture Net Profit ($)", fontsize=11)

for bar in bars:
  height = bar.get_height()
  y_pos = height + 300 if height >= 0 else height - 700
  ax.annotate(
      f"${height:,.0f}",
      xy=(bar.get_x() + bar.get_width() / 2, y_pos),
      ha="center",
      fontweight="bold",
      fontsize=10.5,
  )

plt.title(
    "Slide 5: Central Region Accounts for the Entirety of Net Furniture Losses",
    fontsize=14,
    fontweight="bold",
    pad=18,
    loc="left",
)
plt.suptitle(
    "Takeaway: While the West and East stay profitable, the Central region lost -$2,871 on Furniture due to aggressive regional discount discounting.",
    fontsize=10.5,
    y=0.92,
    x=0.08,
    ha="left",
    color="#475569",
)

plt.tight_layout(rect=[0, 0, 1, 0.90])
plt.savefig(os.path.join(slides_dir, "slide5_regional_evidence.png"), dpi=300)
pdf.savefig(fig)
plt.close()

# ==========================================
# SLIDE 6: RECOMMENDATION SUMMARY
# ==========================================
fig, ax = plt.subplots(figsize=(11, 6.2))
ax.axis("off")

rec_text = """
EXECUTIVE ACTION PLAN: RESTORING PORTFOLIO PROFITABILITY

1. Enforce a Firm 20% Discount Ceiling:
   • Immediately eliminate ad-hoc discounting above 20% across Furniture lines.
   • Requiring director-level approval for exceptions will protect ~85% of currently eroded margins.

2. Restructure the Tables & Bookcases Portfolio:
   • Revise supplier contracts and re-evaluate shipping/freight surcharges for bulky items.
   • Shift sales commissions toward Net Margin contribution rather than raw Top-Line Sales.

3. Fix the Central Region Strategy:
   • Conduct an audit on Central regional pricing agreements to stop localized price wars.
   • Align Central regional discounting strictly with East/West pricing models.
"""

plt.title(
    "Slide 6: Strategic Recommendations to Protect and Grow Operational Margin",
    fontsize=14,
    fontweight="bold",
    pad=18,
    loc="left",
)
plt.suptitle(
    "Takeaway: Executing these 3 operational levers will lift Superstore net profit margins from 12.47% to an estimated 16.5%+.",
    fontsize=10.5,
    y=0.92,
    x=0.08,
    ha="left",
    color="#475569",
)

ax.text(
    0.05,
    0.78,
    rec_text,
    fontsize=11.5,
    linespacing=1.6,
    verticalalignment="top",
    bbox=dict(
        boxstyle="round,pad=1",
        facecolor="#f8fafc",
        edgecolor="#cbd5e1",
        linewidth=1.2,
    ),
)

plt.tight_layout(rect=[0, 0, 1, 0.90])
plt.savefig(os.path.join(slides_dir, "slide6_recommendations.png"), dpi=300)
pdf.savefig(fig)
plt.close()

pdf.close()
print("Execution complete! Story visuals and PDF generated:")
print(f"1. Individual slides saved in: {slides_dir}")
print(f"2. Complete presentation PDF: {pdf_path}")